RVS json logging for iet,gst,pebb and corrections
ROCm-Developer-Tools/ROCmValidationSuite pull request #511
Opened 2021-11-15 14:37 UTC by manoj-freyr

Cleanup and remove redundant info from json logs generated.
Enable changes for pebb reporting

2021-11-16 12:57 UTC, ashutom reviewed
It smells that this is a good opportunity to apply "visitor pattern" here. Have you thought of it?

2021-11-17 00:22 UTC, jkottiku commented
General comment - please check and correct the code indentation.

2021-11-17 06:59 UTC, jkottiku requested changes

2021-11-17 07:02 UTC, jkottiku approved these changes

2021-11-17 07:02 UTC, manoj-freyr commented on pebb.so/include/action.h
> +  void json_add_primary_fields();
this is under assumption that they can be changed independently when we make changes to each module reporting. as of now iet and gst looks similar but they can change independently and that is why it is kept with modules

2021-11-17 07:10 UTC, manoj-freyr commented
> It smells that this is a good opportunity to apply "visitor pattern" here. Have you thought of it?

Wil take it up in next iteration. This was more of removing redundant items from reported json and adding changes to pebb

2021-11-17 07:11 UTC, merged