Fix warning - rocblas reorg path update
ROCm-Developer-Tools/ROCmValidationSuite pull request #538
Opened 2022-04-08 07:08 UTC by arvindcheru

- Updated rocblas include path.

2022-04-12 01:53 UTC, arvindcheru commented
> This change is causing build failure while compiling with ROCm 5.1.
will check with scenario, and will get back. Thanks for notifying this.

2022-06-17 05:58 UTC, arvindcheru commented
> This change is causing build failure while compiling with ROCm 5.1.

Updated Version based checks to enhance this changes. Please check

2022-06-30 20:14 UTC, nunnikri requested changes

2022-06-30 20:14 UTC, nunnikri commented on edp.so/CMakeLists.txt
> +	set(ROCBLAS_MODULE_NM_PREFIX "")
Isnt is better to add this set in the main CMakefile itself. so that same code repeat in not required in multiple sub cmake?

2022-07-05 18:01 UTC, nunnikri approved these changes
Have put some minor suggestion for code cleanup. But the changes are fine as it is.

2022-07-07 04:45 UTC, manoj-freyr approved these changes
lgtm

2022-07-07 15:17 UTC, arvindcheru commented on CMakeLists.txt
> +    message( STATUS "ROCMSMI OLD Version: ${RVS_ROCBLAS_VERSION_FLAT} TO CHECK" )
Removed the additional debug prints in latest version

2022-07-07 23:19 UTC, arvindcheru commented on CMakeLists.txt
> +  #NOTE:Include folders need to be uppated to REORG Folders
Typo will be updated. in latest version

2022-07-07 23:19 UTC, arvindcheru commented on CMakeLists.txt
> +    set(ROCM_SMI_INC_DIR "${ROCM_PATH}/include")
Post reorg changes - ROCM_PATH/include need to be used as include dir

How it work in current rvs: For supporting deprecated version, there will be wrapper provided temporarily (ROCM_PATH/rocm_smi/include and  these are short lived once)  Current version is using these short lived wrappers, hence internal build deprecated warnings generated which serves as a notice to update to latest include dir path. 

This PR is for removing usage of these wrapper and update include dir, which in turn remove the deprecated internal build warning messages due to usage deprecated include dir/files.

2022-07-07 23:22 UTC, jkottiku approved these changes

2022-07-08 00:19 UTC, merged