make regex sensible instead of fixing numbers
ROCm-Developer-Tools/ROCmValidationSuite pull request #557
Opened 2022-10-07 12:21 UTC by manoj-freyr

make sure peqt doesnt depend on deviceid.sh file and no edit after installs. Fix a bug in action.cpp for correct function in pci_caps
deviceid is a field to be fetched from pci in code, removing it from first level confs as it depended on deviceid.sh file. In case filtering needed, provided a default of 0 which can be replaced with appropriate device id by end users,.

2022-10-17 18:06 UTC, jkottiku requested changes

2022-10-17 18:10 UTC, jkottiku commented on src/pci_caps.cpp
> +    //return;
Better we remove this commented line.

2022-10-18 15:18 UTC, manoj-freyr commented on src/pci_caps.cpp
> +    //return;
done

2022-10-18 20:36 UTC, jkottiku approved these changes

2022-11-23 17:42 UTC, merged