ensure max_power updated properly
ROCm-Developer-Tools/ROCmValidationSuite pull request #569
Opened 2022-11-29 14:03 UTC by manoj-freyr

Reporting and udpating max power after a run

2022-11-29 20:00 UTC, jkottiku requested changes

2022-11-30 13:36 UTC, manoj-freyr commented on iet.so/src/iet_worker.cpp
> +            Average power is :" + " " + std::to_string(max_power);
max value will always be updated and it will be the maximum of cur_power_value til now

2022-11-30 13:55 UTC, manoj-freyr commented on iet.so/src/iet_worker.cpp
> +            Average power is :" + " " + std::to_string(max_power);
will add a check

2022-12-07 04:41 UTC, jkottiku approved these changes

2022-12-08 10:39 UTC, merged